h

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -138,50 +138,6 @@ jobs:
           echo "Listing contents of dist:"
           ls -la electron/dist
 
-      # - name: Sign the individual binaries
-      #   run: |
-      #     SIGN_ID="Developer ID Application: Kind Buds, LLC (SRJJDF6WDH)"
-      #     APP_PATH="electron/out/Spence-AI-Career-Autopilot-darwin-universal/Spence-AI-Career-Autopilot.app"
-      #     ENTITLEMENTS="electron/entitlements.plist"
-
-      #     # Sign the main binary
-      #     codesign --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH/Contents/MacOS/Spence-AI-Career-Autopilot"
-
-      #     # Sign each framework individually
-      #     codesign --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework"
-      #     codesign --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH/Contents/Frameworks/ReactiveObjC.framework/Versions/A/ReactiveObjC"
-      #     codesign --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel"
-      #     codesign --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH/Contents/Frameworks/Mantle.framework/Versions/A/Mantle"
-
-      # - name: Sign the entire App bundle
-      #   run: |
-      #     SIGN_ID="Developer ID Application: Kind Buds, LLC (SRJJDF6WDH)"
-      #     APP_PATH="electron/out/Spence-AI-Career-Autopilot-darwin-universal/Spence-AI-Career-Autopilot.app"
-      #     ENTITLEMENTS="electron/entitlements.plist"
-
-      #     # codesign --deep --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH"
-      #     codesign --deep --force --verbose --options runtime --timestamp --entitlements "$ENTITLEMENTS" --sign "$SIGN_ID" "$APP_PATH"
-
-      # - name: Verify the Main App Signature
-      #   run: |
-      #     APP_PATH="electron/out/Spence-AI-Career-Autopilot-darwin-universal/Spence-AI-Career-Autopilot.app"
-      #     # codesign -vvv --deep --strict "$APP_PATH"
-      #     codesign -vvv --deep --strict "$APP_PATH"
-
-      # - name: Package the App as a DMG
-      #   run: |
-      #     APP_PATH="electron/out/Spence-AI-Career-Autopilot-darwin-universal/Spence-AI-Career-Autopilot.app"
-      #     DMG_PATH="electron/out/Spence-AI-Career-Autopilot.dmg"
-
-      #     hdiutil create "$DMG_PATH" -volname "Spence-AI-Career-Autopilot" -srcfolder "$APP_PATH" -ov -format UDZO
-
-      # - name: Sign the DMG
-      #   run: |
-      #     SIGN_ID="Developer ID Application: Kind Buds, LLC (SRJJDF6WDH)"
-      #     DMG_PATH="electron/out/Spence-AI-Career-Autopilot.dmg"
-
-      #     codesign --force --verbose --options runtime --timestamp --sign "$SIGN_ID" "$DMG_PATH"
-
       - name: Notarize the DMG
         run: |
           xcrun notarytool submit electron/dist/Spence-AI-Career-Autopilot.dmg --apple-id "jeff.borden@kindbuds.us" --password "arss-lgut-shmy-ipjl" --team-id "SRJJDF6WDH" --wait
@@ -193,12 +149,6 @@ jobs:
       - name: Verify Stapling
         run: |
           xcrun stapler validate electron/dist/Spence-AI-Career-Autopilot.dmg
-
-      # - name: Upload macOS DMG
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: Spence-AI-Career-Autopilot.dmg
-      #     path: electron/out/Spence-AI-Career-Autopilot.dmg
 
       - name: Upload macOS DMG
         uses: actions/upload-artifact@v4
@@ -277,9 +227,10 @@ jobs:
 
       - name: Install AWS CLI
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
+          sudo ./aws/install -b /usr/local/bin --update > /dev/null 2>&1 || echo "AWS CLI installation failed!"
+          aws --version || echo "AWS CLI not found after installation."
 
       - name: Upload .exe to S3
         run: |
